version: "1"

services:
  - type: web
    name: go-chatroom
    runtime: go
    repo: https://github.com/motty93/go-chatroom
    plan: free
    buildCommand: go build -tags netgo -ldflags '-s -w' -o app
    startCommand: ./app
    region: singapore
    branch: master
    domains:
      - api.paput.io
    healthCheckPath: /health
    autoDeploy: true
    envVars:
      - key: PORT
        value: 8080
      - key: TZ
        value: Asia/Tokyo
